# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: gitversion/setup@0
  displayName: Setup gitversion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Execute gitversion
  inputs:
    useConfigFile: true
    configFilePath: './GitVersion.yml'

- task: DotNetCoreCLI@2
  displayName: Build Example Console
  inputs:
    command: build
    projects: './cdexample/cdexample/cdexample.csproj'
    configuration: 'Debug'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

 
     
- task: CopyFiles@2
  inputs:
    SourceFolder: './cdexample/cdexample/cdexample/bin/Debug/netcoreapp3.1'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cdexample.console'
    publishLocation: 'Container'