# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: gitversion/setup@0
  inputs:
    versionSpec: '5.0.0'
- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: './GitVersion.yml'
  env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)
- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'

- script: 
      $versionInfo = '$($GITVERSION_MAJORMINORPATCH)'
      Write-Host("##vso[task.setvariable variable=Version;]$versionInfo")
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: '$env:Version'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
