# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: gitversion/setup@0
  displayName: Setup gitversion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Execute gitversion
  inputs:
    useConfigFile: true
    configFilePath: './GitVersion.yml'

- task: DotNetCoreCLI@2
  displayName: Build Example Console
  inputs:
    command: build
    projects: './cdexample/cdexample/cdexample.csproj'
    configuration: 'debug'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './cdexample/cdexample/cdexample.csproj'
    
- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: './cdexample/cdexample/cdexample.csproj'
    versioningScheme: byEnvVar
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'cdexample.console'
    publishLocation: 'Container'